version: '3'
services:
    mongodb:
        restart: unless-stopped
        image: 'mongo:${MONGO_VERSION}'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
        volumes:
            - ./docker-volume-mongo:/data/db
        ports:
            - 27017:27017

    backend:
        build: ./backend
        restart: unless-stopped
        ports:
            - 3001:3001
        environment:
            DB_URI: 'mongodb:27017'
            DB_PASSWORD: '${MONGO_PASSWORD}'
            DB_USERNAME: '${MONGO_USERNAME}'
        depends_on:
            - mongodb

    frontend:
        build:
            context: ./frontend
            args:
                VITE_API_PORT: 3001
        restart: unless-stopped
        ports:
            - 80:80
        depends_on:
            - backend
